### ISSUE TITLE
Hello, I am new to vue and I am having trouble getting the application working

### ISSUE THREAD

**Issue by cheseremtitus24** [codedbyEmre/vuetify-movie-store-app#19]
I believe there is an env file that is missing. please provide content of the .env file so as to make it easy to get started with the project.

**Comment by codedbyEmre** [comment]
Hello, thank you for your interest to the project. I have used gitignore file that prevents pushing .env, node module files etc. to the repository. You can create your own .env file that consists of VITE_API_URL variable and its value which is an api key coming from [TMDB](https://www.themoviedb.org/).
